/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RedLibrarian;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *Login prompt for connection to server
 * @author Joseph
 */
public class LoginPrompt extends javax.swing.JFrame {

    /**
     * Indicator of whether the application is or is not connected to the server
     */
    public boolean loggedIn = false;

    /**
     *Username used to log into the server
     */
    public String username = "null";
    
    /**
     * Password used to log into the server
     */
    public String password = "null";
    /**
     * Creates new form LoginPrompt
     */
    public LoginPrompt() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        failed_attempt.setVisible(false);
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_field = new javax.swing.JTextField();
        pass_field = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        user_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        failed_attempt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database Login");
        setType(java.awt.Window.Type.POPUP);

        user_field.setToolTipText("Username");
        user_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_fieldKeyPressed(evt);
            }
        });

        pass_field.setToolTipText("Password");
        pass_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_fieldKeyPressed(evt);
            }
        });

        login_button.setText("Login");
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
        });
        login_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                login_buttonKeyTyped(evt);
            }
        });

        user_label.setText("Username");

        pass_label.setText("Password");

        failed_attempt.setText("Login Unsuccessful!");
        failed_attempt.setForeground(Color.RED);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(login_button)
                                    .addComponent(user_field, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(user_label))
                        .addContainerGap(291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pass_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(failed_attempt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pass_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(failed_attempt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_buttonKeyTyped
        attemptConnection();
    }//GEN-LAST:event_login_buttonKeyTyped

    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseClicked
        attemptConnection();
    }//GEN-LAST:event_login_buttonMouseClicked

    private void pass_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_fieldKeyPressed
        if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            attemptConnection();
    }//GEN-LAST:event_pass_fieldKeyPressed

    private void user_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_fieldKeyPressed
        if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            pass_field.requestFocusInWindow();
    }//GEN-LAST:event_user_fieldKeyPressed

    private void attemptConnection() {
      
       username = this.user_field.getText();
       password = this.pass_field.getText();       
       RedLibrarian.connection = new SQL_JDBC(username,password);
       if(SQL_JDBC.testConnection()) {
           this.setVisible(false);
           loggedIn = true;
           dispose();
       }
       else {
           switch (SQL_JDBC.status) {
               case "driver":
                   failed_attempt.setText("Missing drivers!");
                   break;
               case "credentials":
                   failed_attempt.setText("Invalid credentials!");
                   break;
               case "connectivity":     
                   failed_attempt.setText("Cannot connect to server!");
                   break;
               case "unreported":
                   failed_attempt.setText("Unknown error occurred!");
                   break;
           }
       }
      failed_attempt.setVisible(true);
      pass_field.setText("");
      pass_field.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPrompt().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel failed_attempt;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JLabel pass_label;
    private javax.swing.JTextField user_field;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables
}
