/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redlibrarian.GUI;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import redlibrarian.music.Library;
import redlibrarian.music.Song;

/**
 *
 * @author admir
 */
public class LibraryPane extends javax.swing.JPanel {

    /**
     * Creates new form LibraryPane
     */
    public LibraryPane() {
        initComponents();
    }

    public LibraryPane(Library lib) {
        
        this();
        
        LibraryTableModel model = (LibraryTableModel) table.getModel();
        
        for(Song song : lib.getContents())
            model.addRow(song);
    }
    
    public void updateSong(Song target, Song item) {
        LibraryTableModel model = (LibraryTableModel) table.getModel();
        model.updateRow(model.getSongRow(target), item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new LibraryTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Composer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer(){

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                LibraryTableModel model = (LibraryTableModel) table.getModel();
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(model.getRowColor(row));
                return c;
            }

        };

        renderer.setHorizontalAlignment(SwingConstants.LEFT);
        LibraryTableModel model = (LibraryTableModel) table.getModel();

        for(int x=0; x<model.getColumnCount();x++)
        table.getColumnModel().getColumn(x).setCellRenderer(renderer);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        LibraryTableModel model = (LibraryTableModel) table.getModel();
        Song selectedSong = model.selectRow(table.getSelectedRow());
        
        Object superParent = this.getParent().getParent().getParent().getParent().getParent().getParent();
        if(superParent.getClass().toString().equals(UserInterface.class.toString())) {
            UserInterface userInterface = (UserInterface) superParent;
            userInterface.updateSelection(selectedSong);
        }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private static class LibraryTableModel extends DefaultTableModel {

        private List<Song> rows = new ArrayList<>();
        private List<Color> rowColors = new ArrayList<>();   
        
        private int lastSelectedRow = 0;

        LibraryTableModel(Object [][] obj, String [] str){
            super(obj, str);
        }
        
        private void setRowColor(int row, Color c) {
            if(rowColors.size()>row)
                rowColors.set(row, c);
            else
                rowColors.add(c);
            
            fireTableRowsUpdated(row, row);
        }
        
        private Color getRowColor(int row) {
            if(rowColors.size()>0)
                return rowColors.get(row);
            return null;
        }
        
        private Color determineColor(Song song) {
            if(!song.isAvailable())
                return Color.RED;
            else
                return ((this.getRowCount()+1)%2==0)?Color.WHITE:Color.LIGHT_GRAY;
                
        }
        
        private Color determineColor(Song song, boolean isSelected) {
            if(!isSelected)
                return determineColor(song);
            if(!song.isAvailable())
                return Color.GRAY;
            return Color.YELLOW;
                
        }
        
        
        public boolean addRow(Song song) {
            super.addRow(new Object[]{song.getPseudoId(), song.getTitle(), song.getComposer()});
            this.setRowColor(this.getRowCount(), this.determineColor(song));
            return rows.add(song);
        }
        
        public void updateRow(int row, Song song) {
            super.removeRow(row);
            super.insertRow(row, new Object[]{song.getPseudoId(), song.getTitle(), song.getComposer()});
            this.setRowColor(row, this.determineColor(song));
            rows.set(row, song);
        }
        
        public Song getRow(int row) {
            return rows.get(row);
        }
        
        public int getSongRow(Song song) {
            return rows.indexOf(song);
        }

        public Song selectRow(int selectedRow) {
            Song selectedSong = this.getRow(selectedRow);
            Song previousSong = this.getRow(lastSelectedRow);
            this.setRowColor(lastSelectedRow, this.determineColor(previousSong));
            this.setRowColor(selectedRow, this.determineColor(selectedSong, true));
            lastSelectedRow = selectedRow;
            return  selectedSong;
        }
    }
} 
