/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redlibrarian.GUI;

import java.awt.Color;
import java.awt.Frame;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import redlibrarian.GUI.textVerification.PasswordVerifier;
import redlibrarian.login.ContactDetails;
import redlibrarian.music.Organization;

/**
 *
 * @author admir
 */
@SuppressWarnings("serial")
public class LoginForm extends javax.swing.JDialog {

    private final SessionFactory sessionFactory;
    private boolean loggedIn = false;
    private boolean isAdmin = false;
    private Organization organization;
    
    /**
     * Creates new form LoginForm
     * @param parent
     * @param modal
     * @param sessionFactory
     */
    public LoginForm(java.awt.Frame parent, boolean modal, SessionFactory sessionFactory) {
        super(parent, modal);
        initComponents();
        this.setTitle("Login Prompt");
        loginStatus_label.setVisible(false);
        this.sessionFactory = sessionFactory;
    }
    
    public Organization getOrganization() {
        return organization;
    }
    
    public boolean isLoggedIn() {
        return loggedIn;
    }
    
    public boolean isAdmin() {
        return isAdmin;
    }
    
    public boolean getGuestLoginState() {
        return guest_button.isSelected();
    }
    
    public void setOrganizationText(String org) {
        organization_field.setText(org);
    }
    
        /**
     *
     * @param showAdminLogin
     */
    public void setShowAdminLogin(boolean showAdminLogin) {
        guest_button.setSelected(!showAdminLogin);
    }

    private void attemptLogin() {
        if(organization == null) {
            
            login_button.setEnabled(false);
            
            try {
                Session session = sessionFactory.getCurrentSession();
                session.beginTransaction();
                
                SQLQuery query = session.createSQLQuery("SELECT * FROM Organization WHERE NAME='"+organization_field.getText()+"'");
                query.addEntity(Organization.class);
                
                Organization remoteOrg = (Organization) query.list().get(0);
                
                if(!guest_button.isSelected()) {
                    if(!remoteOrg.verifyPassword(password_field.getText())) {
                        loginStatus_label.setText("INCORRECT");
                        loginStatus_label.setForeground(Color.RED);
                        loginStatus_label.setVisible(true);
                    }
                    else {
                        this.organization = remoteOrg;
                        this.loggedIn = true;
                        this.isAdmin = true;
                        this.setVisible(false);
                    }
                        
                } else {
                    this.organization = remoteOrg;
                    this.loggedIn = true;
                    this.setVisible(false);
                }
            } catch(Exception hibernateException) {
                System.out.println("LOGIN: "+hibernateException);
                if(hibernateException.toString().contains("NullPointerException")) {
                    loginStatus_label.setText("Organization does not exist.");
                }
                
                loginStatus_label.setVisible(true);
                    
            } finally {
                login_button.setEnabled(true);
            }
            
                
        }
    }

    private void processKeyPress(java.awt.event.KeyEvent evt) {
        if (evt.getKeyChar() == (KeyEvent.VK_ENTER)) {
            KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
            manager.focusNextComponent();
            
            if(manager.getFocusOwner().equals(login_button))
                attemptLogin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organization_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        organization_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        loginStatus_label = new javax.swing.JLabel();
        guest_button = new javax.swing.JCheckBox();
        createAccount_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        organization_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                organization_fieldKeyPressed(evt);
            }
        });

        password_field.setInputVerifier(new PasswordVerifier());
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
        });

        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        login_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_buttonKeyPressed(evt);
            }
        });

        organization_label.setLabelFor(organization_field);
        organization_label.setText("Organization");

        password_label.setLabelFor(password_field);
        password_label.setText("Password");

        loginStatus_label.setText("LOGIN STATUS");

        guest_button.setText("Login as guest");
        guest_button.setFocusable(false);
        guest_button.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guest_buttonStateChanged(evt);
            }
        });

        createAccount_label.setForeground(new java.awt.Color(51, 51, 255));
        createAccount_label.setText("Create Account?");
        createAccount_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccount_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(organization_field, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(205, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(login_button))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginStatus_label)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(organization_label, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAccount_label)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guest_button)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organization_label)
                    .addComponent(createAccount_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organization_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label)
                    .addComponent(loginStatus_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(guest_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        attemptLogin();
    }//GEN-LAST:event_login_buttonActionPerformed

    private void guest_buttonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guest_buttonStateChanged
        password_field.setVisible(!guest_button.isSelected()); 
        password_label.setVisible(!guest_button.isSelected());
    }//GEN-LAST:event_guest_buttonStateChanged

    private void organization_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_organization_fieldKeyPressed
        processKeyPress(evt);
    }//GEN-LAST:event_organization_fieldKeyPressed

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyPressed
        processKeyPress(evt);
    }//GEN-LAST:event_password_fieldKeyPressed

    private void login_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_buttonKeyPressed
        processKeyPress(evt);
    }//GEN-LAST:event_login_buttonKeyPressed

    private void createAccount_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccount_labelMouseClicked
        OrganizationForm form = new OrganizationForm((Frame) this.getParent(), true);
        form.setVisible(true);
        
        Organization org = form.getOrganization();
        ContactDetails contact = form.getContact();
        
       org.setContact(contact); 
        
        if(form.wasSaved()) {
            Session session = sessionFactory.getCurrentSession();
            session.beginTransaction();
            
            session.save(org);
            session.save(contact);
            
            session.getTransaction().commit();
        }
        
        form.dispose();
    }//GEN-LAST:event_createAccount_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            LoginForm dialog = new LoginForm(new javax.swing.JFrame(), true, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAccount_label;
    private javax.swing.JCheckBox guest_button;
    private javax.swing.JLabel loginStatus_label;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField organization_field;
    private javax.swing.JLabel organization_label;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    // End of variables declaration//GEN-END:variables



}
